spring.application.name=library

#PostgreSql, JPA
spring.datasource.url = jdbc:postgresql://localhost:5433/librarynew
spring.datasource.username =admin
spring.datasource.password =admin
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto= update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


#JWT
jwt.secret = "956b2c913e70678e200ddb671f1132288b51061dfdd71fd2c4e5b4ded697086d8d7fd2436ea30aba8affd05b1c443cbd5ce6eb235f9fe7197656b0a337ddf15b"
