spring.application.name=library

spring.datasource.url = jdbc:postgresql://localhost:5433/librarynew
spring.datasource.username =admin
spring.datasource.password =admin

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto= update
